# Generated by Django 5.0.3 on 2026-04-21 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_avatar_customuser_bio_customuser_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPRegistrationRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP地址')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='尝试次数')),
                ('last_attempt_at', models.DateTimeField(auto_now=True, verbose_name='最后尝试时间')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='是否被封禁')),
                ('blocked_until', models.DateTimeField(blank=True, null=True, verbose_name='封禁截止时间')),
            ],
            options={
                'verbose_name': 'IP注册限制',
                'verbose_name_plural': 'IP注册限制',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin_user',
            field=models.BooleanField(default=False, verbose_name='管理员权限'),
        ),
        migrations.CreateModel(
            name='UserRegistrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('register', '注册新用户'), ('register_denied', '注册被拒绝'), ('register_failed', '注册失败')], max_length=20, verbose_name='操作类型')),
                ('target_username', models.CharField(blank=True, max_length=150, verbose_name='目标用户名')),
                ('target_email', models.EmailField(blank=True, max_length=254, verbose_name='目标邮箱')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('request_data', models.JSONField(default=dict, verbose_name='请求数据')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_operations', to=settings.AUTH_USER_MODEL, verbose_name='操作管理员')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_records', to=settings.AUTH_USER_MODEL, verbose_name='目标用户')),
            ],
            options={
                'verbose_name': '注册操作日志',
                'verbose_name_plural': '注册操作日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
