# Generated by Django 5.0.3 on 2026-02-01 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='问题标题')),
                ('content', models.TextField(verbose_name='问题内容')),
                ('author', models.CharField(max_length=50, verbose_name='提问者')),
                ('chapter', models.CharField(choices=[('general', '综合讨论'), ('vector', '矢量分析基础'), ('electrostatic', '静电场'), ('magnetostatic', '恒定磁场'), ('maxwell', '麦克斯韦方程组'), ('wave', '平面电磁波'), ('transmission', '传输线理论'), ('waveguide', '波导与谐振腔'), ('antenna', '天线原理'), ('microwave', '微波网络'), ('experiment', '实验答疑')], default='general', max_length=20, verbose_name='所属章节')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
            ],
            options={
                'db_table': 'community_posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='回复内容')),
                ('author', models.CharField(max_length=50, verbose_name='回复者')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_teacher', models.BooleanField(default=False, verbose_name='教师回复')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
            options={
                'db_table': 'community_comments',
                'ordering': ['created_at'],
            },
        ),
    ]
