# Generated by Django 5.0.3 on 2026-02-28 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='课程名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='课程代码')),
                ('description', models.TextField(blank=True, verbose_name='课程描述')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程管理',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='章节名称')),
                ('code', models.CharField(max_length=20, verbose_name='章节代码')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='blog.course', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节管理',
                'ordering': ['course', 'order'],
                'unique_together': {('course', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('single', '单选题'), ('multiple', '多选题'), ('judge', '判断题')], default='single', max_length=10, verbose_name='题型')),
                ('difficulty', models.IntegerField(choices=[(1, '简单'), (2, '中等'), (3, '困难')], default=1, verbose_name='难度')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('options', models.JSONField(default=list, help_text='选项列表，如 ["A. xxx", "B. xxx"]', verbose_name='选项')),
                ('correct_answer', models.CharField(help_text='单选填A/B/C/D，多选填AB/ACD等，判断填T/F', max_length=10, verbose_name='正确答案')),
                ('explanation', models.TextField(verbose_name='答案解析')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='blog.chapter', verbose_name='所属章节')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='blog.course', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=10, verbose_name='用户答案')),
                ('is_correct', models.BooleanField(verbose_name='是否正确')),
                ('practice_time', models.DateTimeField(auto_now_add=True, verbose_name='练习时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.course', verbose_name='课程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.question', verbose_name='题目')),
            ],
            options={
                'verbose_name': '练习记录',
                'verbose_name_plural': '练习记录',
            },
        ),
        migrations.CreateModel(
            name='ErrorNotebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_count', models.IntegerField(default=1, verbose_name='错误次数')),
                ('last_error_time', models.DateTimeField(auto_now=True, verbose_name='最后错误时间')),
                ('is_mastered', models.BooleanField(default=False, verbose_name='是否已掌握')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.course', verbose_name='课程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_notes', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.question', verbose_name='错题')),
            ],
            options={
                'verbose_name': '错题记录',
                'verbose_name_plural': '错题本',
                'unique_together': {('user', 'question')},
            },
        ),
    ]
