# Generated by Django 5.0.3 on 2026-03-01 05:49

import blog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_course_chapter_question_practicerecord_errornotebook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='资料标题')),
                ('description', models.TextField(blank=True, verbose_name='资料描述')),
                ('file', models.FileField(upload_to=blog.models.course_file_path, verbose_name='文件')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('file_type', models.CharField(choices=[('ppt', 'PPT课件'), ('pdf', 'PDF文档'), ('video', '视频'), ('code', '代码/程序'), ('data', '数据文件'), ('other', '其他')], default='other', max_length=10, verbose_name='文件类型')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('require_login', models.BooleanField(default=True, verbose_name='需要登录')),
                ('download_count', models.IntegerField(default=0, verbose_name='下载次数')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='blog.chapter', verbose_name='所属章节')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='blog.course', verbose_name='所属课程')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '课程资料',
                'verbose_name_plural': '课程资料管理',
                'ordering': ['-upload_time'],
            },
        ),
        migrations.CreateModel(
            name='DownloadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_time', models.DateTimeField(auto_now_add=True, verbose_name='下载时间')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='blog.coursematerial', verbose_name='资料')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '下载记录',
                'verbose_name_plural': '下载记录',
                'ordering': ['-download_time'],
            },
        ),
    ]
