# Generated by Django 5.0.3 on 2026-04-10 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_coursematerial_downloadrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='事件标题')),
                ('date', models.DateField(verbose_name='日期')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='时间')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='地点')),
                ('event_type', models.CharField(choices=[('theory', '理论课'), ('lab', '实验课'), ('exam', '考试'), ('assignment', '作业'), ('review', '复习'), ('other', '其他')], default='other', max_length=20, verbose_name='事件类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '日历事件',
                'verbose_name_plural': '日历事件管理',
                'ordering': ['-date', '-time'],
                'indexes': [models.Index(fields=['user', 'date'], name='blog_calend_user_id_86bd65_idx')],
            },
        ),
    ]
