# Generated by Django 5.0.3 on 2026-04-27 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_user_post_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.CreateModel(
            name='ChapterProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_id', models.CharField(help_text='格式：course_code/chapter_code，如 ee/ch1', max_length=50, verbose_name='章节ID')),
                ('chapter_name', models.CharField(max_length=100, verbose_name='章节名称')),
                ('course_code', models.CharField(help_text='ee=电磁场, mw=微波工程', max_length=20, verbose_name='课程代码')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否已完成')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_progress_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '章节学习进度',
                'verbose_name_plural': '章节学习进度管理',
                'ordering': ['-completed_at', '-updated_at'],
                'unique_together': {('user', 'chapter_id')},
            },
        ),
    ]
