# Generated by Django 5.0.3 on 2026-04-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_comment_user_remove_post_user_chapterprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterprogress',
            name='completed_subtasks_count',
            field=models.PositiveIntegerField(default=0, verbose_name='已完成子任务数'),
        ),
        migrations.AddField(
            model_name='chapterprogress',
            name='subtasks',
            field=models.JSONField(blank=True, default=dict, help_text='存储各学习小点的完成状态', verbose_name='子任务进度'),
        ),
        migrations.AddField(
            model_name='chapterprogress',
            name='total_subtasks_count',
            field=models.PositiveIntegerField(default=0, verbose_name='总子任务数'),
        ),
    ]
